name: Build with Makefile
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: sudo apt-get update && sudo apt-get install -yq build-essential git libsdl2-dev libsdl2-ttf-dev libsdl2-net-dev

      - uses: actions/checkout@v2
      - name: Build project
        run: make

  windows_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_net

      - uses: actions/checkout@v2
      - name: Build project
        run: make WINDOWS=1